"""@generated by tools/gen_commissioning_vocabulary.py from vocabulary.toml. Do not edit."""

PHASE_NAMES: dict[int, str] = {
    1: "ADC calibration",
    2: "Coil check",
    3: "Phase wiring",
    4: "Encoder check",
    5: "Electrical ID",
    6: "Current tune",
    7: "Current validation",
    8: "Inner done",
    18: "Breakaway proportional acquisition",
    19: "Integral gain response characterization",
    20: "Fixed-gain amplitude validation",
    21: "Reversal standstill robustness gate",
    16: "Encoder alignment",
    17: "Closed-loop entry",
    26: "Gain floor measurement",
}

BREAKAWAY_PHASE_NAMES: dict[int, str] = {
    0: "breakaway_probe",
    1: "proportional_response_discovery",
    2: "proportional_band_confirmation",
}

ACTION_CODES: dict[str, int] = {
    "amplitude_up": 1,
    "amplitude_down": 2,
    "breakaway_seeded": 7,
    "integral_resume": 8,
    "robustness_reversal": 9,
}

SHAPE_RESUME = 0
SHAPE_FIXED_GAIN_AMPLITUDE_ASCENDING = 1
SHAPE_FIXED_GAIN_AMPLITUDE_DESCENDING = 2
SHAPE_BREAKAWAY_SEEDED = 3
SHAPE_ROBUSTNESS_REVERSAL = 4

WORKFLOW_SHAPE_TO_AMPLITUDE_ORDER: dict[int, int] = {
    SHAPE_FIXED_GAIN_AMPLITUDE_ASCENDING: 1,
    SHAPE_FIXED_GAIN_AMPLITUDE_DESCENDING: 2,
}
