"""Shared constants for the klipper-foci host module."""

MIN_RAW_VOLTAGE_LIMIT = 0
MIN_OPERATIONAL_VOLTAGE_LIMIT = 1024
DEFAULT_OPERATIONAL_VOLTAGE_LIMIT = 16000
MAX_DIAGNOSTIC_VOLTAGE_LIMIT = 32767
MAX_RUN_CURRENT_AMPS = 5.0
PID_GAIN_MAX_RAW = 0x7FFF
