"""Shared constants for the klipper-foci host module."""

MIN_RAW_VOLTAGE_LIMIT = 0
MIN_OPERATIONAL_VOLTAGE_LIMIT = 1024
DEFAULT_OPERATIONAL_VOLTAGE_LIMIT = 16000
MAX_DIAGNOSTIC_VOLTAGE_LIMIT = 32767
FOCI_MAX_RUN_CURRENT_MA_CONSTANT = "FOCI_MAX_RUN_CURRENT_MA"
PID_GAIN_MAX_RAW = 0x7FFF
ELECTRICAL_ID_WAIT_TIMEOUT_S = 30.0

ELECTRICAL_MODEL_RESISTANCE_SCALE = 1000

FIRMWARE_DEFAULT_VELOCITY_LIMIT = 500_000

COMMISSION_CANCEL_GRACE_PERIOD_S = 2.0
